<?php
/**
 * @var $this Template
 * @var $contactsModel ProductModel
 * @var $categoriesModel ShopingCartModel
 */


$orderModel = $this->getModel('orders');
$ordercartModel = $this->getModel('ordercart');
$orderstatusModel = $this->getModel('status');


/**
 * @var $contacts array of Product
 */
$ordercarts = $ordercartModel->getAll();
$orderstatuses = $orderstatusModel->getAll();

?>

<?php include_once('elements/head.phtml'); ?>

<?php include_once('elements/menu.phtml'); ?>


<h1>
    <small><?php echo "Zamówienia w realizacji" . ' (';
        echo count($ordercarts) . ')' ?></small>
</h1>
<hr>
<div>
    <a href="?action=ordercartlistdetail">

        <button type="button" class="btn btn-success">
            <span class="glyphicon glyphicon-plus">Szczegóły</span>
        </button>
    </a>
</div>
<hr>
<table id="table" class="table table-striped table-hover">

    <thead>
    <tr>
        <th>#</th>
        <th>Nr zamówienia</th>
        <th>Nazwa klienta</th>
        <th>Numer wewnętrzny zamówienia klienta</th>
        <th>Data zamówienia</th>
        <th>Termin realizacji</th>
        <th>Status</th>
        <th>Tydzień nr</th>
        <th>Akcje</th>

    </tr>
    </thead>
    <tbody>


    <?php
    /**
     * @var $order Order
     */

    foreach ($ordercarts as $nr => $ordercart):
        $order = $orderModel->getOneById($ordercart->getOrderid());
        ?>
        <tr>
            <form name="form" id="form" method="post" class="myforms">

                <th scope="row"><?php echo $nr + 1; ?></th>

                <td><input class="form-check" hidden name="model[ordercart][<?php echo $nr; ?>][orderid]"
                           value="<?php echo $order->getId(); ?>"
                           id="flexCheckDefault<?php echo $nr; ?>"><?php if (!empty($order)) echo $order->getCustomerorderida() . "/" . $order->getCustomerorderidb(); ?>
                </td>
                <td><input class="form-check" hidden name="model[ordercart][<?php echo $nr; ?>][ordercustomername]"
                           value="<?php echo $order->getCustomername(); ?>"
                           id="flexCheckDefault<?php echo $nr; ?>"><?php if (!empty($order)) echo $order->getCustomername(); ?>
                </td>
                <td><?php if (!empty($order)) echo $order->getCustomerexternalorderid(); ?></td>
                <td><?php if (!empty($order)) echo $order->getOrderdate(); ?></td>
                <td><?php if (!empty($order)) echo $order->getOrderdeadline(); ?></td>
                <td><select class='form-control' name="model[ordercart][<?php echo $nr; ?>][orderstatus]"
                            id="model[ordercart][<?php echo $nr; ?>][orderstatus]" required>
                        <option value='<?php if (!empty($order)) {
                        echo $order->getOrderstatus(); ?>'
                                selected><?php echo $order->getOrderstatus();
                            } else {
                                echo "disabled selected>Wybierz status>";
                            } ?></option><?php
                        foreach ($orderstatuses as $status) {
                            ?>
                            <option value="<?php echo $status->getStatus(); ?>"><?php echo $status->getStatus(); ?></option>
                        <?php } ?>

                    </select></td>
                <td><?php if (!empty($order)) echo $order->getOrderpositioninschedule(); ?></td>
            </form>
            <td><a href="?action=orderdetail&id=<?php echo $order->getId(); ?>"
                   data-placement="right">
                    <button class="btn btn-danger">Szczegóły
                    </button>
                </a>
            </td>

        </tr>

    <?php


    endforeach; ?>
    </tbody>

</table>

<button id="allsubmit" class="btn btn-success float-right">Zapisz</button>
<script>

    $("#allsubmit").on("click", function () {
        $('.myforms').each(function () {
            $(this).submit();

        });
    });
</script>


<?php include_once('elements/footer.phtml'); ?>
