<?php
/**
 * @var $this Template
 * @var $contactsModel ProductModel
 * @var $categoriesModel ShopingCartModel
 */


$orderModel = $this->getModel('orders');
$ordercartModel = $this->getModel('ordercart');
$orderstatusModel = $this->getModel('orderstatus');

/**
 * @var $contacts array of Product
 */
$orders = $orderModel->getAll();

$orderstatuses = $orderModel->getAll();
$holdid = '';
?>

<?php include_once('elements/head.phtml'); ?>

<?php include_once('elements/menu.phtml'); ?>
<div class="up_button">
    <a href="?action=orderaddedit"
       data-toggle="tooltip" title="Add order" data-placement="left">
        <button type="button" class="btn btn-success">
            <span class="glyphicon glyphicon-plus">Dodaj zamówienie</span>
        </button>
    </a>
    <button id="allsubmit" class="btn btn-success float-right">Dodaj do realizowanych</button>
</div>


<h1>
    <small><?php echo "Lista zamówień" . ' (';
         echo count($orders) . ')' ?></small>
</h1>
<hr>
<h5>Legenda</h5>
<div class="btn-group">
    <button class="btn-secondary">Nie rozpoczęte</button>
    <button class="btn-warning">W realizacji</button>
    <button class="btn-success">Gotowe</button>
    <button class="btn-danger">Wysłane</button>
</div>
<hr>
<table id="table" class="table table-striped table-hover">

    <thead>
    <tr>
        <th>#</th>
        <th>#</th>
        <th>Nr zamówienia</th>
        <th>Nazwa klienta</th>
        <th>Numer wewnętrzny zamówienia klienta</th>
        <th>Data zamówienia</th>
        <th>Termin realizacji</th>
        <th>Status</th>
        <th>Tydzień nr</th>
        <th>Akcje</th>

    </tr>
    </thead>
    <tbody>
    <form name="form" id="form" method="post" class="myforms">

        <?php
        /**
         * @var $order Order
         */

        foreach ($orders as $nr => $order):

            ?>
            <tr <?php if (!empty($order)) {
                if ($order->getOrderstatus() == "Nie rozpoczęte") echo 'class="table-secondary"';
                if ($order->getOrderstatus() == "W realizacji") echo 'class="table-warning"';
                if ($order->getOrderstatus() == "Gotowe") echo 'class="table-success"';
                if ($order->getOrderstatus() == "Wysłane") echo 'class="table-danger"';
            } ?>>

                <th scope="row"><?php echo $nr + 1; ?></th>
                <td>
                    <input class="form-check" hidden name="model[ordercart][<?php echo $nr; ?>][id]"
                           value="" id="flexCheckDefault<?php echo $nr; ?>">
                    <input class="form-check" hidden name="model[ordercart][<?php echo $nr; ?>][ordercartstatus]"
                           value="0" id="flexCheckDefault<?php echo $nr; ?>">
                    <input class="form-check" hidden name="model[ordercart][<?php echo $nr; ?>][cartid]" value="0"
                           id="flexCheckDefault<?php echo $nr; ?>">

                    <input class="form-check-input" type="checkbox" name="model[chosen][]" value="<?php echo $nr; ?>"
                           id="flexCheckDefault<?php echo $nr; ?>">

                </td>
                <td><input class="form-check" hidden name="model[ordercart][<?php echo $nr; ?>][orderid]"
                           value="<?php echo $order->getId(); ?>"
                           id="flexCheckDefault<?php echo $nr; ?>"><?php if (!empty($order)) echo $order->getCustomerorderida() . "/" . $order->getCustomerorderidb(); ?>
                </td>
                <td><input class="form-check" hidden name="model[ordercart][<?php echo $nr; ?>][ordercustomername]"
                           value="<?php echo $order->getCustomername(); ?>"
                           id="flexCheckDefault<?php echo $nr; ?>"><?php if (!empty($order)) echo $order->getCustomername(); ?>
                </td>
                <td><?php if (!empty($order)) echo $order->getCustomerexternalorderid(); ?></td>
                <td><?php if (!empty($order)) echo $order->getOrderdate(); ?></td>
                <td><?php if (!empty($order)) echo $order->getOrderdeadline(); ?></td>
                <td><?php if (!empty($order)) echo $order->getOrderstatus(); ?></td>
                <td><?php if (!empty($order)) echo $order->getOrderpositioninschedule(); ?></td>
                <td>
                    <button class="btn btn-danger"><a href="?action=orderaddedit&id=<?php echo $order->getId(); ?>"
                                                      data-placement="right">Edytuj </a>
                    </button>


                    <button class="btn btn-danger"><a href="?action=orderdelete&id=<?php echo $order->getId(); ?>"
                                                      data-placement="right">Usuń</a>
                    </button>
                </td>

            </tr>

        <?php endforeach; ?></form>
    </tbody>

</table>
<button id="allsubmit" class="btn btn-success float-right">Dodaj do realizowanych</button>
<script>

    $("#allsubmit").on("click", function () {
        $('.myforms').each(function () {
            $(this).submit();

        });
    });
</script>



<?php include_once('elements/footer.phtml'); ?>
