<?php

$projectbuypartModel = $this->getModel('projectbuypart');


?>
<div class="tab-pane" id="buypart" role="tabpanel" aria-labelledby="settings-tab">
    <table class="table table-bordered" id="projectbuyparttable">

        <thead>
        <tr>
            <td>#</td>
            <td>Nazwa przedmiotu</td>
            <td>Ilość</td>
            <td>Rozmiar</td>
            <td>Wymiar A</td>
            <td>Wymiar B</td>
            <td>Uwagi - Indeks zakupowy</td>
        </tr>
        </thead>
        <tbody>

        <?php
        if (!empty($project)) {


            $projectbuyparts = $projectbuypartModel->getMatchingProject($projectindex, $projectversion, $projectsize);
            $nr = 0;
            if (!empty($projectbuyparts)) {
                foreach ($projectbuyparts as $nr => $projectbuypart):?>
                    <tr>
                        <input type="hidden" name="model[projectbuypart][<?php echo $nr; ?>][id]"
                               value="<?php if (!empty($projectbuypart)) echo $projectbuypart->getId(); ?>">
                        <input type="hidden" name="model[projectbuypart][<?php echo $nr; ?>][projectsize]"
                               value="<?php if (!empty($projectbuypart)) echo $projectbuypart->getProjectsize(); ?>">
                        <input type="hidden" name="model[projectbuypart][<?php echo $nr; ?>][projectversion]"
                               value="<?php if (!empty($projectbuypart)) echo $projectbuypart->getProjectversion(); ?>">
                        <input type="hidden" name="model[projectbuypart][<?php echo $nr; ?>][projectid]"
                               id="model[projectbuypart][<?php echo $nr; ?>][projectid]"
                               value="<?php if (!empty($projectbuypart)) echo $projectbuypart->getProjectid(); ?>">
                        <td><input type="text" class="form-control"
                                   name="model[projectbuypart][<?php echo $nr; ?>][buypartid]"
                                   id="model[projectbuypart][<?php echo $nr; ?>][buypartid]" placeholder=""
                                   value="<?php if (!empty($projectbuypart)) echo $projectbuypart->getBuypartid(); ?>">
                        </td>
                        <td><input type="text" class="form-control"
                                   name="model[projectbuypart][<?php echo $nr; ?>][buypartname]"
                                   id="model[projectbuypart][<?php echo $nr; ?>][buypartname]" placeholder=""
                                   value="<?php if (!empty($projectbuypart)) echo $projectbuypart->getBuypartname(); ?>">
                        </td>
                        <td><input type="text" class="form-control"
                                   name="model[projectbuypart][<?php echo $nr; ?>][buypartamount]"
                                   id="model[projectbuypart][<?php echo $nr; ?>][buypartamount]" placeholder=""
                                   value="<?php if (!empty($projectbuypart)) echo $projectbuypart->getBuypartamount(); ?>">
                        </td>
                        <td><input type="text" class="form-control"
                                   name="model[projectbuypart][<?php echo $nr; ?>][buypartsize]"
                                   id="model[projectbuypart][<?php echo $nr; ?>][buypartsize]" placeholder=""
                                   value="<?php if (!empty($projectbuypart)) echo $projectbuypart->getBuypartsize(); ?>">
                        </td>
                        <td><input type="text" class="form-control"
                                   name="model[projectbuypart][<?php echo $nr; ?>][buypartdima]"
                                   id="model[projectbuypart][<?php echo $nr; ?>][buypartdima]" placeholder=""
                                   value="<?php if (!empty($projectbuypart)) echo $projectbuypart->getBuypartdima(); ?>">
                        </td>
                        <td><input type="text" class="form-control"
                                   name="model[projectbuypart][<?php echo $nr; ?>][buypartdimb]"
                                   id="model[projectbuypart][<?php echo $nr; ?>][buypartdimb]" placeholder=""
                                   value="<?php if (!empty($projectbuypart)) echo $projectbuypart->getBuypartdimb(); ?>">
                        </td>
                        <td><input type="text" class="form-control"
                                   name="model[projectbuypart][<?php echo $nr; ?>][buypartnotes]"
                                   id="model[projectbuypart][<?php echo $nr; ?>][buypartnotes]" placeholder=""
                                   value="<?php if (!empty($projectbuypart)) echo $projectbuypart->getBuypartnotes(); ?>">
                        </td>
                    </tr>
                <?php endforeach;
            }
        }
        ?>
        </tbody>
    </table>
</div>