<?php
$projectModel = $this->getModel('project');
$projects = $projectModel->getAll();


include_once('elements/head.phtml');
include_once('elements/menu.phtml');
?>
    <h1>
        <small><?php echo "Lista projektów"; ?></small>
    </h1>
    <hr>
    <table id="table" class="table table-striped table-hover">

        <thead>
        <tr>
            <th>#</th>
            <td>Nazwa projektu</td>
            <td>Rozmiar</td>
            <td>Typ</td>
            <td>Informacje dodatkowe</td>
            <td>Akcje</td>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($projects as $nr => $project):

            ?>
            <tr>
                <td><?php echo $nr + 1; ?></td>
                <td><?php if (!empty($project)) echo $project->getProjectname(); ?></td>
                <td><?php if (!empty($project)) echo $project->getProjectsize(); ?></td>
                <td><?php if (!empty($project)) echo $project->getProjectversion(); ?></td>
                <td><?php if (!empty($project)) echo $project->getProjectnotes(); ?></td>
                <td>
                    <a href="?action=projectaddedit&id=<?php echo $project->getId(); ?>"
                       data-placement="right"><button class="btn btn-success">Edytuj
                    </button>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>

        </tbody>
    </table>

<?php

include_once('elements/footer.phtml'); ?>