<?php include_once('elements/head.phtml'); ?>
<?php include_once('elements/menu.phtml'); ?>


    <div class="col-sm-10 center">
        <button class="btn btn-success float-left">Lewo</button>
        <button class="btn btn-success float-right">Prawo</button>
        <h1><small>Tydzień 35</small></h1>
        <hr>

        <!-- Code by w3codegenerator.com -->
        <table class="table  table-bordered table-striped">
            <thead class="table-success">
            <tr>
                <th>#</th>
                <th>Nazwa klienta</th>
                <th>Nr zamówienia</th>
                <th>Nr zamówienia klienta</th>
                <th>Data zamówienia</th>
                <th>Status</th>
                <th>Akcje</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>Mark</td>
                <td>Otto</td>
                <td>@mdo</td>
                <td>Mark</td>
                <td>Otto</td>
                <td>@mdo</td>
                <td>@mdo</td>
            </tr>
            </tbody>
        </table>
    </div>

<?php include_once('elements/footer.phtml'); ?>