<?php
$shipmentModel = $this->getModel('shipment');
$shipments=$shipmentModel->getAllShiped();


include_once('elements/head.phtml'); ?>
<?php include_once('elements/menu.phtml'); ?>

    <h1>
        <small><?php echo "Wysłane zamówienia"; ?></small>
    </h1>
    <hr>
    <table id="table" class="table table-striped table-hover">

        <thead class="table-light">
        <tr>
            <th>#</th>
            <th>Nr zamówienia</th>
            <th>Nazwa klienta</th>
            <th>Numer wewnętrzny zamówienia klienta</th>
            <th>Data zamówienia</th>
            <th>Termin realizacji</th>
            <th>Akcje</th>

        </tr>
        </thead>
        <tbody>

        <?php
        /**
         * @var $shipment Order
         */

        foreach ($shipments as $nr => $shipment):

            ?>
            <tr>

                <th scope="row"><?php echo $nr + 1; ?></th>
                <td><?php if (!empty($shipment)) echo $shipment->getCustomerorderida() . "/" . $shipment->getCustomerorderidb(); ?>
                </td>
                <td><?php if (!empty($shipment)) echo $shipment->getCustomername(); ?>
                </td>
                <td><?php if (!empty($shipment)) echo $shipment->getCustomerexternalorderid(); ?></td>
                <td><?php if (!empty($shipment)) echo $shipment->getOrderdate(); ?></td>
                <td><?php if (!empty($shipment)) echo $shipment->getOrderdeadline(); ?></td>
                <td>
                    <button class="btn btn-danger"><a href="?action=orderaddedit&id=<?php echo $shipment->getId(); ?>"
                                                      data-placement="right">Edytuj</a>
                    </button>
                </td>

            </tr>

        <?php endforeach; ?>
        </tbody>

    </table>

<?php include_once('elements/footer.phtml'); ?>