<div class="container-fluid">
    <div class="row content">
        <div class="col-sm-2 sidenav">
            <br>
            <br>
            <ul class="list-group col-auto">
                <h5 class="list-group-header">Plan produkcji</h5>
                <li class="list-group-item"><a href="?action=schedulelist">Aktualny tydzień</a></li>
                <li class="list-group-divider"></li>
                <h5 class="list-group-header">Realizowane</h5>
                <li class="list-group-item"><a href="?action=ordercartlist">Lista zamówień</a></li>
                <li class="list-group-item"><a href="?action=preparelists">Przygotuj listy produkcyjne</a></li>
                <li class="list-group-divider"></li>
                <h5 class="list-group-header">Listy produkcyjne</h5>
                <li class="list-group-item"><a href="?action=listbuypart">Elementy zakupowe</a></li>
                <li class="list-group-item"><a href="?action=listlaser">Laser</a></li>
                <li class="list-group-item"><a href="?action=listmaterial">Materiał</a></li>
                <li class="list-group-divider"></li>
                <h5 class="list-group-header">Zamówienia</h5>
                <li class="list-group-item"><a href="?action=orderlist">Lista zamówień</a></li>
                <li class="list-group-item"><a href="?action=orderaddedit">Dodaj</a></li>
                <li class="list-group-divider"></li>
                <h5 class="list-group-header">Projekty</h5>
                <li class="list-group-item"><a href="?action=projectlist">Lista</a></li>
                <li class="list-group-item"><a href="?action=projectaddedit">Dodaj</a></li>
                <li class="list-group-divider"></li>
                <h5 class="list-group-header">Wysyłka</h5>
                <li class="list-group-item"><a href="?action=shipmentlist">Lista</a></li>
                <li class="list-group-divider"></li>
            </ul>
            <br>
        </div>
        <div class="col-sm-10 " style="padding:50px!important">

